version: "3.7"


networks:
  elastic:
    driver: bridge

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    working_dir: /application
    volumes:
      - ${DOCKER_STORAGE_PATH}/database:/var/lib/mysql
      - ..:/application
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - elastic

  webserver:
    image: nginx:alpine
    container_name: nginx
    working_dir: /application
    volumes:
        - ..:/application
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ${DOCKER_STORAGE_PATH}/logs/nginx:/var/log/nginx/
    ports:
     - "${APP_PORT}:80"
     - "${APP_SSL_PORT}:443"
    networks:
      - elastic
                
  php-fpm:
    build: ./php-fpm
    container_name: php-server
    working_dir: /application
    volumes:
      - ..:/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: ${ELASTICSEARCH_HOSTNAME}
    hostname: ${ELASTICSEARCH_HOSTNAME}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    networks:
      - elastic
          
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: ${KIBANA_HOSTNAME}
    hostname: ${KIBANA_HOSTNAME}
    ports:
    environment:
      ELASTICSEARCH_URL: http://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}
      ELASTICSEARCH_HOSTS: http://${ELASTICSEARCH_HOSTNAME}:${ELASTICSEARCH_PORT}
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - elastic
    
    

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - frontend

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: kibana
    ports:
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - frontend

  # mailcatcher:
  #   image: jeanberu/mailcatcher
  #   container_name: mailcatcher
  #   restart: always
  #   ports:
  #     - "1025:1025"
  #     - "1080:1080"


